### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by razilong** [YenalyLiew/Han1meViewer#10]
①倍速
②前进10s，后退10s的(叠加层)控件，
③直接在视频上左右划拉即可移动进度条

塞个内核是不是就可以了？

(有人说看里番打手冲开倍速干嘛，我觉得有人也一样会嫌AV和里番演员动作慢而开1.5倍的)

**Comment by YenalyLiew** [comment]
不是，除了第二个这不一直有吗，你没装最新版本吗

**Comment by YenalyLiew** [comment]
ok，我到时候看看

**Comment by gankumangcao** [comment]
> 不是，除了第二个这不一直有吗，你没装最新版本吗

长按倍速支持一手，希望能在设置里能调倍速倍率，有人的喜欢1.5倍 有的2.0我站2.0

**Comment by YenalyLiew** [comment]
已添加默认倍速
