### ISSUE TITLE
［Feat］關鍵幀移出設定

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#104]
### 描述您建議的功能

增加關鍵幀的權重 不再是設定的一部分 而是功能的一部分 把關鍵幀放在側邊欄設定的下方或許是個好選擇

### 其他你想講的

![Screenshot_2024-04-03-00-55-42-515_com.yenaly.han1meviewer-edit.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/111511925/16bb549f-60fb-4259-8648-2be85e95f3d9)

**Comment by YenalyLiew** [comment]
确实
