### ISSUE TITLE
［Feat］共享幀劇集分類

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#106]
### 描述您建議的功能

可根據標題分類 加個二級菜單之類的
或者是在源用資料夾分類

**Comment by YenalyLiew** [comment]
![Screenshot_2024-04-04-12-10-12-003_com.yenaly.han1meviewer.debug.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/92662107/fd1cd2e0-15e8-42ae-a45e-2cc223009e76)

初改版，但我还是想把ui改改，但没什么思路

**Comment by NeKoOuO** [comment]
我在想是不是能做成像資料夾的方式
點進去是集數名稱 然後再點進去才是一到六集之類的

**Comment by NeKoOuO** [comment]
> 初改版，但我还是想把ui改改，但没什么思路

因為如果像這樣排的話他還是會有順序 如果要看不同系列的話一樣要一直滾動

**Comment by NeKoOuO** [comment]
> 我在想要是能把每个番的封面当作背景就好了，但是我没接口，硬请求的话估计直接把ip给你ban了🥹

我也想過當背景 但是總覺得會過多請求🤔

**Comment by YenalyLiew** [comment]
> 我在想是不是能做成像資料夾的方式
> 點進去是集數名稱 然後再點進去才是一到六集之類的

ui可以做，但文件夹不太适合，因为用文件夹的话，打开一个影片需要遍历所有文件夹找，而全部放在根目录的情况下只需要查找对应代号就可以了
