### ISSUE TITLE
［Feat］完善利用JSON 資訊

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#107]
### 描述您建議的功能

目前還有一個 author 沒顯示
我不確定 prompt 顯不顯示

### 其他你想講的

![Screenshot_2024-04-03-00-59-52-334_com yenaly han1meviewer](https://github.com/YenalyLiew/Han1meViewer/assets/111511925/ee9d508a-fe37-49c7-99fd-e23bbd6743ad)

**Comment by YenalyLiew** [comment]
prompt显示的，你没写prompt就隐藏
