### ISSUE TITLE
简中界面播放器设置还是繁体

### ISSUE THREAD

**Issue by ZerOri** [YenalyLiew/Han1meViewer#112]
### 實際行為

![Screenshot_2024-04-05-19-03-01-292_com yenaly han1meviewer](https://github.com/YenalyLiew/Han1meViewer/assets/46775615/6eb8c651-a430-45b1-a6c1-1e5c384fe63e)
RT，望下版修正。

### 預期行為

这个不算bug吧，不过强迫症犯了还是提个issue。

### Han1meViewer version

0.14.0

### Android version

Andriod 13

### Device

红米k40

**Comment by YenalyLiew** [comment]
我去看看

**Comment by YenalyLiew** [comment]
下版本解决，感谢
