### ISSUE TITLE
[bug] 横屏全屏时，按侧边返回，变成竖屏，然后因为是横屏状态，又变回横屏

### ISSUE THREAD

**Issue by Minori-ty** [YenalyLiew/Han1meViewer#113]
### 實際行為

横屏全屏时，按侧边返回。此时保持横屏状态，app播放变成竖屏，然后因为是横屏状态，又变回横屏。

### 預期行為

希望在横屏状态时，侧边返回，直接退出全屏.

并且希望增加一个像b站一样的，长按屏幕快进功能。

### Han1meViewer version

v0.14.0+24032514

### Android version

Android 13

### Device

小米10

**Comment by Minori-ty** [comment]
https://github.com/YenalyLiew/Han1meViewer/assets/79521943/7af6c7d5-d63d-468f-aa9b-ccdc2309181f

**Comment by YenalyLiew** [comment]
长按屏幕快进一直有啊？？

**Comment by Minori-ty** [comment]
> 长按屏幕快进一直有啊？？

好的，不过没那么灵敏

**Comment by YenalyLiew** [comment]
我有一个问题，你一开始手机是处于什么状态？
横屏+软件占中间一小部分？还是竖屏？
你在点击全屏的时候，从横向竖屏变为了纵向竖屏，不是很理解怎么做到的

**Comment by Minori-ty** [comment]
https://github.com/YenalyLiew/Han1meViewer/assets/79521943/dae510b8-639d-489a-8301-7ae5ae391fa2

**Comment by Minori-ty** [comment]
不知道可不可以算作可以优化的地方？

**Comment by NeKoOuO** [comment]
> 
> https://github.com/YenalyLiew/Han1meViewer/assets/79521943/dae510b8-639d-489a-8301-7ae5ae391fa2
> 
> 

你把重力加速度傳感器關掉就好

**Comment by YenalyLiew** [comment]
> 不知道可不可以算作可以优化的地方？

真麻烦你了，还专门录了视频。🙇
现在我知道了，我抽空看看问题在哪

**Comment by Minori-ty** [comment]
> > 不知道可不可以算作可以优化的地方？
> 
> 真麻烦你了，还专门录了视频。🙇 现在我知道了，我抽空看看问题在哪

关掉了旋转，好像就解决了。辛苦您了
