### ISSUE TITLE
Support Deeplink

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#124]
### 描述您建議的功能

Android 12 的功能

**Comment by YenalyLiew** [comment]
deeplink是什么

**Comment by NeKoOuO** [comment]
https://private-user-images.githubusercontent.com/111511925/316699256-388ac05b-79ca-4830-8916-c7253a187472.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNTMxODQsIm5iZiI6MTcxMzE1Mjg4NCwicGF0aCI6Ii8xMTE1MTE5MjUvMzE2Njk5MjU2LTM4OGFjMDViLTc5Y2EtNDgzMC04OTE2LWM3MjUzYTE4NzQ3Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQwMzQ4MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjE1NjIzMmZmZDAyOWYzOTY5MDRhMmUzZTkwMjMwYjgzNTNlNWZiNDZkNzViMjkxM2UzNzM3YmQ5NGIyNTgwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3ns8LdzX9JSqNnJUcRW1aMac2OhxXU9clS3ticmBLKw

**Comment by NeKoOuO** [comment]
![Screenshot_2024-03-26-09-42-03-841_com.android.settings.jpg](https://github.com/xiaoyvyv/bangumi/assets/111511925/388ac05b-79ca-4830-8916-c7253a187472)

**Comment by YenalyLiew** [comment]
我都不知道有这玩意。。

**Comment by NeKoOuO** [comment]
> 我都不知道有这玩意。。

哈哈哈沒事 這東西超好用的

**Comment by YenalyLiew** [comment]
好像这东西一直支持。。我很早就实现过的

**Comment by NeKoOuO** [comment]
> 好像这东西一直支持。。我很早就实现过的

真假 因為我自己實際點連結是不會自己跳轉的

**Comment by NeKoOuO** [comment]
我錄個範例

https://github.com/YenalyLiew/Han1meViewer/assets/111511925/c4e33f74-fed2-4c5d-9876-a5a3983f34f9

**Comment by YenalyLiew** [comment]
我用adb调试却能直接跳转，怪了，我再看看

**Comment by YenalyLiew** [comment]
![Screenshot_2024-04-17-18-31-21-411_com.android.settings.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/92662107/3f25dece-8848-45b7-8704-ce851e46f1ce)

我不理解，明明有写

**Comment by NeKoOuO** [comment]
> ![Screenshot_2024-04-17-18-31-21-411_com.android.settings.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/92662107/3f25dece-8848-45b7-8704-ce851e46f1ce)
> 
> 我不理解，明明有写

我覺得可能是你沒有加入口

所以他默認是關的

**Comment by YenalyLiew** [comment]
>  
> > 我不理解，明明有写
> 
> 我覺得可能是你沒有加入口
> 
> 因為他默認是關的

你用的哪个第三方pixiv，我去抄抄

**Comment by NeKoOuO** [comment]
https://github.com/Notsfsssf/pixez-flutter

**Comment by YenalyLiew** [comment]
我去还真是，MIUI默认没有这个界面，我说怎么不行呢，你真是帮大忙了！![Screenshot_2024-04-17-22-49-35-270_com.android.settings.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/92662107/1b5c1ac9-685f-4e03-9768-401a01347b4e)

**Comment by YenalyLiew** [comment]
但是这个选项一直存在，你从应用信息那里面能自己打开，MIUI把这个选项隐藏了

**Comment by NeKoOuO** [comment]
> 但是这个选项一直存在，你从应用信息那里面能自己打开，MIUI把这个选项隐藏了

對 要用特殊方法才能打開
