### ISSUE TITLE
长按快进有bug

### ISSUE THREAD

**Issue by Minori-ty** [YenalyLiew/Han1meViewer#129]
### 實際行為

小米10，长按快进有bug，没有快进，并且是回退几秒。

### 預期行為

希望修复

### Han1meViewer version

0.14.5+24042003

### Android version

13

### Device

小米10

### 其他

并且希望修改一下筛选图标，一开始看到还有点懵逼。

可以考虑换成b站那种，https://www.iconfont.cn/search/index?searchType=icon&q=%E7%AD%9B%E9%80%89

![image](https://github.com/YenalyLiew/Han1meViewer/assets/79521943/6528590c-958d-4039-b22c-0e683c0248aa)

**Comment by YenalyLiew** [comment]
1. 快进有bug

这个问题难解决，我打算到时候换一下视频播放组件，这个有点老，问题有点多不太好改

2. 换图标

我觉得也对，到时候换一个

**Comment by gankumangcao** [comment]
加1，我米9长按快进也有问题

**Comment by YenalyLiew** [comment]
> 加1，我米9长按快进也有问题

你也跟他一个问题吗

**Comment by gankumangcao** [comment]
> > 加1，我米9长按快进也有问题
> 
> 你也跟他一个问题吗

是的，打开一个作品播放，第一次长按快进会倒退几秒后，松开后再用长按快进就是正常的了，退出作品再打开首次长按快进还会触发bug。
(流程是这样的，打开作品播放第一次长按快进会倒退几秒，倒退时间后自动给松开了但我手还在长按中，等于第一次长按触发的是倒退时间功能，触发一次bug后后面的长按快进就是正常的了，但退出作品后再从新打开或播放第二集也还会出这bug。

**Comment by YenalyLiew** [comment]
搞好了，换了个播放器内核

**Comment by YenalyLiew** [comment]
#130 
可能解决了你们快进回退的问题，但是我不确定用起来到底还有没有其他bug，你们如果有空可以帮我测试一下，谢谢大家了！
具体更新方法，打开设置中的ci更新渠道，就能收到更新了。如果bug比较多但又不能回退，你也可以到播放器设置里把内核切换回MediaPlayer，也就是原来的内核。

**Comment by Minori-ty** [comment]
> #130 
> 可能解决了你们快进回退的问题，但是我不确定用起来到底还有没有其他bug，你们如果有空可以帮我测试一下，谢谢大家了！
> 具体更新方法，打开设置中的ci更新渠道，就能收到更新了。如果bug比较多但又不能回退，你也可以到播放器设置里把内核切换回MediaPlayer，也就是原来的内核。
> 
> 如果你不希望一直测试版更新，等ci更新完可以关闭ci更新，待下次稳定版更新就会只给你推送稳定版了

没问题了
