### ISSUE TITLE
人机检测一直无法通过

### ISSUE THREAD

**Issue by soybottle-j** [YenalyLiew/Han1meViewer#132]
### 實際行為

登录的时候一直无法通过人机检测，检测之后又要继续检测，换过多个节点都不行

### 預期行為

这个能修吗？

### Han1meViewer version

v0.14.5

### Android version

Andriod 13

### Device

CLK-AN00

**Comment by NeKoOuO** [comment]
網路環境的問題

**Comment by YenalyLiew** [comment]
现在登录还需要人机检测了？

**Comment by soybottle-j** [comment]
> 现在登录还需要人机检测了？

app登录不知道为什么有个人机检测，网页没有

**Comment by YenalyLiew** [comment]
网络问题
