### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by razilong** [YenalyLiew/Han1meViewer#14]
最新版v0.10.6
①默认倍速经常不生效，重启一下，生效了，下下次再打开又失效。

②
【三键导航】时，右上角的“倍速”控件，怎么点都是变成触发状态栏(下图)，没法选择倍速![20230920_171749_rmscr.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/97635957/70353ca8-cc97-4119-91e3-0214067a7476)
其它控件正常

【全面屏手势导航】这时倍速控件能点击了，点击速度后app闪退

如果可以，给开发者反馈一下！
These errors occurred:
java.lang.NullPointerException:
Attempt to write to null array
 at 
com.yenaly.han1meviewer.ui.view.Cul
stomJzvdStd.setCurrentSpeedIndex(
CustomJzvdStd.kt:118)
 at 
com.yenaly.han1meviewer.ui.view.Cu
stomJzvdStd.access$setCurrentSpee
dindex(CustomJzvdStd.kt:39)
 at 
com.yenaly.han1meviewer.ui.view.Cu
stomJzvdStd$speedPopup$2.invoke$
lambda$0(CustomJzvdStd.kt:126)
 at 
com.yenaly.han1meviewer.ui.view.Cu
stomJzvdStd$speedPopup$2.$r8$la_
mbda$xTO1UJ006WcyHV_327hS3a0H
p7o(Unknown Source:0)
 at 
com.yenaly.han1meviewer.ui.view.Cul
stomJzvdStd$speedPopup$2$
$ExternalSyntheticLambda0.onSelect
(Unknown Source:2)
 at
com.lxj.xpopup.impl.AttachListPopup
View$2.onltemClick(AttachListPopup
View.java:86)
 at
com.lxj.easyadapter.MultiltemTypeAd
apter.setListener$lambda-0(Multilte
mTypeAdapter.kt:70)
 at
com.lxj.easyadapter.MultiltemTypeAd
apter.
$r8$lambda$uqfb58lcjGNtfRb2skdch
m3CLns(Unknown Source:0)
 at
com.lxj.easyadapter.MultiltemTypeAd
apter$
$ExternalSyntheticLambda0.onclick(
Unknown Source:4)
 at
android.view.View.performClick(Vie
w.java:7766)
 at
android.view.View.performClickInter
nal(View.java:7739)
 at
android.view.View.access$3700(View.java:860)
 at
android.view.View$PerformClick.run(
View.java:29330)
 at
android.os.Handler.handleCallback(H 
andler.java:938)
 at
android.os.Handler.dispatchMessage(
Handler.java:99）
 at
android.os.Looper.LoopOnce(Looper.j
ava:210)
 at
android.os.Looper.loop(Looper.java:2
99）
 at
android.app.ActivityThread.main(Acti
vityThread.java:8306)
 at
java.lang.reflect.Method.invoke(Nati
ve Method)
 at
com.android.internal.os.Runtimelnit$
MethodAndArgsCaller.run(Runtimelni
t.java:576)
 at
com.android.internal.os.Zygotelnit.m
ain(Zygotelnit.java:1073)

📱MIUI13  Android12

**Comment by YenalyLiew** [comment]
我擦我也是MIUI啊，我完全复现不了你的问题，我这里测试没有你的这些bug。。
等我有空再看看

**Comment by YenalyLiew** [comment]
三键确实有问题，回头我看看

**Comment by YenalyLiew** [comment]
我这里修复了，你升级一下0.10.7试试看
