### ISSUE TITLE
你好，为什么下载的视频没封面

### ISSUE THREAD

**Issue by qwoan** [YenalyLiew/Han1meViewer#145]
### 實際行為

之前的版本就这样，更新了新版本也这样，新下载的有封面，之前的没了，过一段时间封面全没了

### 預期行為

没封面

### Han1meViewer version

0.14.8

### Android version

13

### Device

k20pro

**Comment by YenalyLiew** [comment]
我后面也发现了这个问题，说简单点就是我保存的是那个图片的网址，但是那个网址是有**时效性**的，所以就会导致历史记录前面一部分显示的好好的，后面全挂了
目前还没什么好的解决思路，你们肯定也不想每次去缓存一个视频封面去占储存空间

**Comment by qwoan** [comment]
好的，谢谢

**Comment by qwoan** [comment]
> 我后面也发现了这个问题，说简单点就是我保存的是那个图片的网址，但是那个网址是有**时效性**的，所以就会导致历史记录前面一部分显示的好好的，后面全挂了 目前还没什么好的解决思路，你们肯定也不想每次去缓存一个视频封面去占储存空间

好吧
