### ISSUE TITLE
网站昨天受到攻击了 目前暂时修复好了 但是现在应用内的连接没有用了

### ISSUE THREAD

**Issue by c2707413730** [YenalyLiew/Han1meViewer#147]
大佬能不能临时修复一下连接😰 辛苦大佬

**Comment by YenalyLiew** [comment]
修复不了，等墙自动消失

**Comment by c2707413730** [comment]
> 修复不了，等墙自动消失

好吧~_~ 看来大部分知名的网站都被DDoS攻击了 现在都启动cloudflare保护原因 已经失效了是吗 还是感谢大佬这么长时间以来做出的贡献 有赞助渠道吗？

**Comment by YenalyLiew** [comment]
> > 修复不了，等墙自动消失
> 
> 好吧~_~ 看来大部分知名的网站都被DDoS攻击了 现在都启动cloudflare保护原因 已经失效了是吗 还是感谢大佬这么长时间以来做出的贡献 有赞助渠道吗？

谢谢支持！他们网站最近刚被DDoS，所以他们防护等级可能暂时会调的高一点，过上几天或者几周避避风头可能就恢复了
