### ISSUE TITLE
搜索和播放界面被顶部状态栏遮罩

### ISSUE THREAD

**Issue by yanecc** [YenalyLiew/Han1meViewer#149]
### 實際行為

搜索和播放界面被顶部状态栏遮罩
![Screenshot_20240601_225436](https://github.com/YenalyLiew/Han1meViewer/assets/89304297/1b6e4b6f-b10d-41e1-867a-50fab83ea371)
![Screenshot_20240601_225843](https://github.com/YenalyLiew/Han1meViewer/assets/89304297/33a9f40d-8ed1-42df-9200-feb33fbe3ac1)

### 預期行為

和任何其他界面一样在状态栏下方完整显示内容
![Screenshot_20240601_225636](https://github.com/YenalyLiew/Han1meViewer/assets/89304297/b37bbec6-da34-412f-8a9b-1a4a40f90245)

### Han1meViewer version

v0.14.8

### Android version

Android 14

### Device

Nubia Z50

**Comment by YenalyLiew** [comment]
@NeKoOuO 你有这问题吗

**Comment by NeKoOuO** [comment]
無

**Comment by YenalyLiew** [comment]
你看看解决了没，更新最新版本试试，有问题再跟我说
