### ISSUE TITLE
能出类似于绿ehv那种系统代理吗

### ISSUE THREAD

**Issue by YingYeGui** [YenalyLiew/Han1meViewer#15]

**Comment by YenalyLiew** [comment]
我去学习一下

**Comment by YenalyLiew** [comment]
![IMG_20231006_180051.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/92662107/dd794f25-2089-4360-a948-a08e25d8fe07)

你是说这种吗

**Comment by YingYeGui** [comment]
对的这种系统代理，主要是直连的延迟太高了，只有凌晨才能有机会连接。

**Comment by YenalyLiew** [comment]
新版本 v0.10.8 有了，你去试试能不能用，不能用再跟我说一声。因为我基本没有这个需求，我也不好调试，谢谢了

**Comment by YingYeGui** [comment]
好我现在去试试，基本一天不会有什么进不去的情况就ok了，偶尔卡顿也是没问题的，谢谢你的付出，我也不太会调试，如果过段时间没什么问题我就回来说一声

**Comment by YingYeGui** [comment]
emmm

**Comment by YingYeGui** [comment]
我这边没有调试信息之类的东西，
![EFA1CBD730E6E0FF0310882E7E152EF2](https://github.com/YenalyLiew/Han1meViewer/assets/110084144/bf0aa44f-3be3-46d4-9f1f-76e0e1f688ea)
不过可能延迟还是gao高了

**Comment by YenalyLiew** [comment]
好像ehv默认就是系统代理。。

我还以为你是有http和socks的那个需求。。

**Comment by YenalyLiew** [comment]
你这个问题应该是没挂梯子，而不是这个代理问题

**Comment by YingYeGui** [comment]
![KU}32J`XETE 0T68CO5BY~2](https://github.com/YenalyLiew/Han1meViewer/assets/110084144/8740c3ad-33a2-4dc9-9291-06071d3d8ead)
的确没有梯子，ehv那个还是有直连的，不过代理可以让我不用梯子也能比较低延迟看东西，所以我就想说有没有机会来一个，我这个延迟偶尔还是能直连上h站的不过很少机会，基本凌晨

**Comment by YingYeGui** [comment]
绿e那个代理偶尔有点小卡顿不过问题不大，系统代理后可以直连

**Comment by YingYeGui** [comment]
![Y4P _Z694VZ37848)F FWYX](https://github.com/YenalyLiew/Han1meViewer/assets/110084144/514db662-c73d-4221-9a88-6bdc70e7af8b)
看看有没有机会，如果不行就算了，辛苦你了

**Comment by YenalyLiew** [comment]
主要是ehv众人拾柴火焰高，他们能直连应该是应用外的其他功能实现的。我这里如果不开梯子，ehv直连和系统代理都连不上，可能是区域问题。

**Comment by YingYeGui** [comment]
不太清楚，我这边ehv系统代理，不管是校园网还是家里网络或者流量都能进去只不过是快慢问题，偶尔有点小卡顿，用流量会快很多

**Comment by YingYeGui** [comment]
如果用ehv的直连或者其他模式我是打不开的

**Comment by YingYeGui** [comment]
我这边ehv是系统代理，pixivfunc用的是本地反代来看pixiv的东西，

**Comment by YingYeGui** [comment]
我觉得可以借鉴一下，pixivfunc这个应用的本地反代看看，ehv和pixivfunc在github都有不过就是目前阶段我还不是很懂里面的代码

**Comment by YingYeGui** [comment]
其他的ehv不怎么用，主要用绿e，缺点是登录可能要梯子，我绿e登录是用的免费一天的梯子
