### ISSUE TITLE
一直检查更新失败怎么回事

### ISSUE THREAD

**Issue by yijianxing** [YenalyLiew/Han1meViewer#152]
### 實際行為

一直检查更新失败怎么回事

### 預期行為

大概什么时候可以更新好

### Han1meViewer version

v0.14.8

### Android version

Originos

### Device

vivo iqoo

**Comment by YenalyLiew** [comment]
1. 更新额度用光了
2. 你没挂梯子所以GitHub无法访问

**Comment by yijianxing** [comment]
现在hanime我挂好多梯子都进不去

**Comment by YenalyLiew** [comment]
自己的问题

**Comment by yijianxing** [comment]
好嘞谢谢了
