### ISSUE TITLE
更新

### ISSUE THREAD

**Issue by chennian520** [YenalyLiew/Han1meViewer#155]
### 實際行為

无法检查更新

### 預期行為

希望更新番快点

### Han1meViewer version

0.14.0

### Android version

13

### Device

手机

### 其他

无

**Comment by NeKoOuO** [comment]
更新番是網站問題 此app只提供觀看功能

**Comment by YenalyLiew** [comment]
这是个毛bug，乱加tag干啥

**Comment by YenalyLiew** [comment]
#152

**Comment by NeKoOuO** [comment]
@YenalyLiew 如果一直出現更新問題可以試試 https://mirror.ghproxy.com

**Comment by YenalyLiew** [comment]
> @YenalyLiew 如果一直出現更新問題可以試試 https://mirror.ghproxy.com

OK
