### ISSUE TITLE
0.10.8版本，网络连接会绕过系统VPN

### ISSUE THREAD

**Issue by rurires** [YenalyLiew/Han1meViewer#16]
正常情况下选择默认的系统代理应该会遵循系统VPN设置，也就是像没有代理设置功能的普通软件那样。
0.10.8新增代理设置功能后，几乎所有的连接都会绕过VPN，但偶尔也会有读取主页、评论的时候走VPN。（也不排除是我手机系统原因。）

其实 #15 提到的ehv直连是应对域名被阻断的情况，对于ha1这种本来就能连上但很慢的情况是没有帮助的。

软件内代理设置主要是用于梯子挂在局域网的其它设备上然后供单个软件转发，或者进程之间自定义转发(，电脑上还好，手机上应该很少这样用)。
保留这个功能然后修复网络连接表现也是多多益善，但对于这样一个可能大多数人基本用不到的功能在精力有限的情况下其实可以考虑回滚掉？

**Comment by YenalyLiew** [comment]
感谢提问，以下是关键代码处。

https://github.com/YenalyLiew/Han1meViewer/blob/master/app/src/main/java/com/yenaly/han1meviewer/HProxySelector.kt

这些代码基本上抄的是ehv的代理模式，默认是“系统代理”。而且如果走系统代理，里面的代码最后也会走到 getDefault() 方法，相当于系统默认的 ProxySelector。

主要是我这里没什么问题，运行很良好，代码逻辑似乎也没什么问题。我看看如果反响这个问题的人多了，下个版本就删了吧。

**Comment by YenalyLiew** [comment]
> 其实 #15 提到的ehv直连是应对域名被阻断的情况，对于ha1这种本来就能连上但很慢的情况是没有帮助的。

我还以为他是有那个代理的需求，主要我一般挂个梯子就能上了，所以对ehv里面那一大堆网络设置其实不是太了解用处。

上个月我们这里把ha1给反诈了，本来想搞个和ehv之类的安全DNS，结果一直没搞成，还好这个月给取消了。网络相关的东西是挺复杂的。。

**Comment by rurires** [comment]
再试了试发现应该是我弄错了，实际上选择系统代理后是和之前的版本表现一样的。
开始是遇到软件设置里的检查更新一直失败，然后误解了Clash的日志记录方式，以为是软件没走代理。
抱歉抱歉。

**Comment by YenalyLiew** [comment]
> 再试了试发现是我弄错了，实际上选择系统代理后是和之前的版本表现一样的。
> 开始是遇到软件设置里的检查更新一直失败，然后误解了Clash的日志记录方式，以为是软件没走代理。
> 抱歉抱歉。

检查更新失败一般是因为GitHub api调用有上限，因为每次进入设置界面都会请求一下GitHub的api来检查有没有新版本，所以用的人一多就可能超过上限导致失败。

**Comment by YingYeGui** [comment]
我才看懂一点是，绿ehv是通过内置了hosts映射和绕过了sni封锁来达到国内直连的，我刚才试过了不是代理问题

**Comment by YingYeGui** [comment]
我没有了解完整，我的问题
