### ISSUE TITLE
高级搜索月份日期

### ISSUE THREAD

**Issue by xuehantian** [YenalyLiew/Han1meViewer#161]
大佬，可以在高级搜索的日期里增添全部月份吗？就是只筛选年份不筛选月份。

**Comment by YenalyLiew** [comment]
官网能这么筛选吗？

**Comment by xuehantian** [comment]
> 官网能这么筛选吗？

可以的
![Uploading Screenshot_2024-07-05-16-23-08-784_com.android.chrome.jpg…]()
