### ISSUE TITLE
增加訂閱功能

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#162]
### 描述您建議的功能

現在原網站好像可以訂閱創作者

可以在APP裡面加這個功能

**Comment by YenalyLiew** [comment]
ok但我最近没啥时间，有空再说吧！

**Comment by YenalyLiew** [comment]
有一说一，你说订阅那个界面放在哪里比较好？搜索位置，还是单独开个界面？但我感觉他这个订阅太简陋了，本质就是个搜索功能，为这个做一个界面太大材小用了

**Comment by NeKoOuO** [comment]
你是說進去的地方嗎？
