### ISSUE TITLE
提示浏览器不安全，谷歌登录不了

### ISSUE THREAD

**Issue by djwlx** [YenalyLiew/Han1meViewer#165]
### 實際行為

提示浏览器不安全，谷歌登录不了

### 預期行為

提示浏览器不安全，谷歌登录不了
![Screenshot_2024-07-11-11-22-43-265_com yenaly han](https://github.com/YenalyLiew/Han1meViewer/assets/58622651/cfc7e668-5dfc-47ed-a453-84b485cbfcba)

### Han1meViewer version

0.14.8

### Android version

14

### Device

小米14

**Comment by YenalyLiew** [comment]
#29 修不了
