### ISSUE TITLE
如何登錄帳戶？

### ISSUE THREAD

**Issue by pimp1234** [YenalyLiew/Han1meViewer#17]
無法登陸

**Comment by YenalyLiew** [comment]
左划抽屉点击左上角不是能登吗

**Comment by pimp1234** [comment]
顯示：
您目前使用的瀏覽器不支援或已停用 JavaScript。
如要確保 Google 帳戶安全，請嘗試登入已啟用 JavaScript 的瀏覽器。

**Comment by YenalyLiew** [comment]
> 顯示：
> 您目前使用的瀏覽器不支援或已停用 JavaScript。
> 如要確保 Google 帳戶安全，請嘗試登入已啟用 JavaScript 的瀏覽器。

你用的谷歌登录是吧，暂时还不支持谷歌登录抱歉，以后看看能不能做好

**Comment by YenalyLiew** [comment]
把js打开也不行，谷歌禁止这种登录方式，只能用官方登录了
