### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by fuhuodazuoze** [YenalyLiew/Han1meViewer#173]
### 實際行為

現在無法加載視頻封面，也無法搜索視頻觀看，只能觀看下載的視頻

### 預期行為

最初只是以為加速器的問題導致視頻封面沒有加載

### Han1meViewer version

v0.14.8+24070612

### Android version

PD2156_A_5.22.13

### Device

OriginOS ocean

### 其他

![Screenshot_20240724_180215](https://github.com/user-attachments/assets/098402d6-fcae-43d4-832c-335811008b35)

**Comment by acdcbyl** [comment]
貌似是网站炸了
