### ISSUE TITLE
下载时出现问题

### ISSUE THREAD

**Issue by axlmly** [YenalyLiew/Han1meViewer#177]
在网站的下载地址出现问题后，软件内下载开始时不会出现错误提示，下载界面也无法显示要下载的目标，本地会正常创建文件，大小停留在0b，过一段时间后会提示下载报错。
下载目标：少交女1

**Comment by YenalyLiew** [comment]
回去试试

**Comment by YenalyLiew** [comment]
我去，我这里咋下载正常啊？

**Comment by axlmly** [comment]
> 我去，我这里咋下载正常啊？

又找到个可以试出问题的 [maenchu] 酒吞童子 [Fate/Grand Order]

**Comment by axlmly** [comment]
> 哦我明白了，我这里有处理，内部有三次重试机会，默认是30s+指数上升，所以弹窗得好几分钟之后才会出现
> 下个版本还是重试三次，但是内部改成10s+线性，一分钟内就会弹窗结果

还有已下载的条目是会存储在数据库里防止重复下载这个逻辑能再优化成重复下载会有提示并且有重新下载吗，

**Comment by YenalyLiew** [comment]
> > 哦我明白了，我这里有处理，内部有三次重试机会，默认是30s+指数上升，所以弹窗得好几分钟之后才会出现
> > 下个版本还是重试三次，但是内部改成10s+线性，一分钟内就会弹窗结果
> 
> 还有已下载的条目是会存储在数据库里防止重复下载这个逻辑能再优化成重复下载会有提示并且有重新下载吗，

你重新开一个issue然后提个功能建议
