### ISSUE TITLE
CI签名不一致 看到这里的先暂时不要通过CI更新

### ISSUE THREAD

**Issue by tmby** [YenalyLiew/Han1meViewer#196]
### 實際行為

打开CI更新通道，新版本的签名与旧版本不一致无法覆盖安装

### 預期行為

CI签名一致，可以覆盖安装

### Han1meViewer version

v0.14.10+24082715

### Android version

Android 12

### Device

Huawei Nova 9 Pro

**Comment by YenalyLiew** [comment]
你从旧版本更新到新版本可以安装吗？还是只有CI的有问题？我排查下

**Comment by YenalyLiew** [comment]
之前你在0.14.8到0.14.10的时候出问题了吗

**Comment by tmby** [comment]
> 之前你在0.14.8到0.14.10的时候出问题了吗

0.14.8到0.14.10的更新没有问题
https://github.com/user-attachments/assets/694bbe9d-400d-43fb-9ef9-21039e1c4399

有问题的是0.14.10开始的CI更新
https://github.com/user-attachments/assets/a956ad7b-fc69-4a10-88d6-4c2c5d0b050a

**Comment by YenalyLiew** [comment]
我去，还真是，怎么回事妈的

**Comment by YenalyLiew** [comment]
ok明天就解决了
