### ISSUE TITLE
没有登录失败的校验

### ISSUE THREAD

**Issue by eventhorizonsky** [YenalyLiew/Han1meViewer#2]
即使密码错误登录失败，也会回到首页，并载入错误的用户数据![Screenshot_20221102_014225_com.yenaly.han1meviewer.jpg](https://user-images.githubusercontent.com/60322987/199302249-bee1767f-ea40-4aa6-8d62-e813b8866f04.jpg)

**Comment by YenalyLiew** [comment]
解决了，感谢issue
