### ISSUE TITLE
UI Bug 

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#202]
來回報一些🐛 這問題存在挺久的了
- [ ] 勾選/取消勾選 

加入清單不會正確刷新 只有退出當前頁面並返回才會正常顯示
- [ ] 喜歡/不喜歡

這個跟上一個也一樣 但是觸發機率比較低

https://github.com/user-attachments/assets/b37c2b8f-61a6-4e3e-8fdf-e4a78b3bf8b9

https://github.com/user-attachments/assets/fb35d623-5c89-4ce1-bc15-31b86a4f7611

**Comment by YenalyLiew** [comment]
触发概率低=没有🤓☝️

**Comment by NeKoOuO** [comment]
不等式秒了
