### ISSUE TITLE
評論區bug

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#203]
有時候查看評論區的時候 不會正常刷新 
可復現 機率大概20%左右
> 然後我覺得可以在加載這個頁面的時候 就順便加載評論區的留言了(改成惰性加載或是後加載感覺不錯) 切到評論區還要再加載一次有點怪

https://github.com/user-attachments/assets/670ccef7-6340-4455-a605-101f694209db

**Comment by YenalyLiew** [comment]
我直接进行一个预加载
