### ISSUE TITLE
收藏重複bug

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#204]
這個其實跟 #202 應該有關聯 
如果要復現 只要在原本的地方 加入清單重複操作 就會有重複收集了
~~然後喜歡的影片好像也會有這個問題 不過我也不確定怎麼復現~~

- [x] 我的清單重複
![Screenshot_2024-09-07-01-09-37-041_com.yenaly.han1meviewer-edit.jpg](https://github.com/user-attachments/assets/fc84cc71-b52b-4f80-b411-d888e17f03c8)
- [x] 喜歡影片重複

**Comment by YenalyLiew** [comment]
#202 解决了这个应该也不会有啥问题了

**Comment by YenalyLiew** [comment]
这个牛肉封面挺好看

**Comment by NeKoOuO** [comment]
> 这个牛肉封面挺好看

我也覺得

**Comment by YenalyLiew** [comment]
我复现了
