### ISSUE TITLE
新增類型

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#207]
### 描述您建議的功能

現在類型分區多了一個 MMD

**Comment by YenalyLiew** [comment]
这个你可以帮忙添加下，我不是把类型什么的拆成json了吗

**Comment by NeKoOuO** [comment]
誤會了 我指的是這個
![image](https://github.com/user-attachments/assets/a606e8d6-9c6c-48c8-9cf4-7759e34de681)

**Comment by YenalyLiew** [comment]
这个栏目我在app里也没做啊

**Comment by YenalyLiew** [comment]
![Screenshot_2024-09-11-16-28-44-666_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/fd40c1ff-7e82-465c-be4f-8fba569ff7a7)

![Screenshot_2024-09-11-16-29-33-957_com.github.android-edit.jpg](https://github.com/user-attachments/assets/b69b2a02-9096-4954-8fa8-b5a44b37651b)

我知道啊，他再怎么说也只是个分类啊，从这里面加上就好了

**Comment by NeKoOuO** [comment]
哦哦 看來是我誤會了 我以為你講的是關鍵幀的結構
