### ISSUE TITLE
发布日期添加功能

### ISSUE THREAD

**Issue by zjlhhjy** [YenalyLiew/Han1meViewer#211]
### 描述您建議的功能

Hope to be able to add a release date when the user chooses a few years, such as: (October 2000 can show the current year of animation)
需要一个在发布日期 年月日（如：选择2000年0月可以选择2000一整年的动漫）

### 其他你想講的

If more hope can be an old animation area to find the old fan before more cumbersome release date is not flexible.
如果更可以希望可以出一个老动漫区 找以前的老番比较繁琐 发布日期不灵活

**Comment by 19810665725** [comment]
此功能ci频道已经实现，猜你想说选定动漫时间范围，如(2000-2010)年，方便老番选区

**Comment by YenalyLiew** [comment]
> 此功能ci频道已经实现，猜你想说选定动漫时间范围，如(2000-2010)年，方便老番选区

这个网页支持吗？

**Comment by 19810665725** [comment]
> > 此功能ci频道已经实现，猜你想说选定动漫时间范围，如(2000-2010)年，方便老番选区
> 
> 这个网页支持吗？

很抱歉，仍未找到解决方式。网页并没有直接提供选区功能。

**Comment by 19810665725** [comment]
不过是不是可以自行创造一个检索库，将固定年份的影片依次放进去，然后按观看次数降序排列。如:
①2021.300万次②2019.200万次③2015.100万次
