### ISSUE TITLE
无法下载

### ISSUE THREAD

**Issue by lbrony** [YenalyLiew/Han1meViewer#218]
### 實際行為

在影片页面点击下载后，什么也不发生，在不久后弹出横幅提示“下载（影片名）……”，由于影片名一般很长，所以无法看到横幅的完整内容

### 預期行為

点击下载按钮后立刻开始下载

### Han1meViewer version

0.14.8

### Android version

origin os 4

### Device

iqoo neo9 pro

**Comment by lbrony** [comment]
补充，只有部分视频出现这个情况，但是无法区分具体什么类型的视频出现这个情况

**Comment by YenalyLiew** [comment]
有的就是下载不了，过一段时间下载看看

**Comment by wowj123** [comment]
怎么下次不了了

**Comment by wowj123** [comment]
怎么不能下载软件 Ha1
