### ISSUE TITLE
最新Han1meViewer出现的0问题

### ISSUE THREAD

**Issue by nomisi1** [YenalyLiew/Han1meViewer#221]
### 實際行為

登录时间几个小时弹出后他的真人认证按真常流程过不了，而且连登录按钮都没有了

### 預期行為

可以把登录功能强化一下

### Han1meViewer version

v0.15.0

### Android version

Android14

### Device

OPPO K12 5G

**Comment by YenalyLiew** [comment]
登录按钮都没有了？给个登录按钮都没有了的截图

**Comment by nomisi1** [comment]
![Screenshot_2024-09-26-10-36-12-00_5f9b2ef4da6ea616cfec4a63e3cc44b3.jpg](https://github.com/user-attachments/assets/b6395e5a-333f-4173-afee-fdcd813d48d5)

**Comment by nomisi1** [comment]
也不能说没有了把，就是有些不灵然后看不了

**Comment by laiteboat** [comment]
看不了评论区啊
![IMG_20241003_141829](https://github.com/user-attachments/assets/a2bbcba6-8a7c-4684-9707-26bb6450781e)
