### ISSUE TITLE
APP无法观看

### ISSUE THREAD

**Issue by roop2666** [YenalyLiew/Han1meViewer#231]
### 實際行為

打开显示为，他们网址加固了不知道什么时候修复

### 預期行為

我想知道什么时候可以修复

### Han1meViewer version

V0.15.0

### Android version

14

### Device

Xiaomi14

**Comment by ixilebone** [comment]
换一个域名试试。设置-网络设置-域名

**Comment by YenalyLiew** [comment]
他们网址加固了不知道什么时候（网站拥有方）修复

跟我没有关系

**Comment by roop2666** [comment]
我发现了，他现在是晚上关闭，谢谢大佬



---原始邮件---
发件人: "Yenaly ***@***.***&gt;
发送时间: 2024年10月10日(周四) 上午9:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YenalyLiew/Han1meViewer] APP无法观看 (Issue #231)




 
他们网址加固了不知道什么时候（网站拥有方）修复
 
跟我没有关系

**Comment by Rongjie7** [comment]
貌似是从晚上12点到早上10点加固
