### ISSUE TITLE
按下Playlist时的登录错误

### ISSUE THREAD

**Issue by INKCR0W** [YenalyLiew/Han1meViewer#234]
### 實際行為

当我处于未登录状态，按下菜单栏中```My List```一栏中的三个按钮时，都会提示需要先进行登录并跳转到登录界面，
前面两个（```Watch Later```和```Favorite Videos```）的登录都没有问题，
但是当我按下```Playlist```并在跳转的页面中登录，在主页刷新后会立即提示登录失效

### 預期行為

应该和前两个按钮一样可以正常登录

### Han1meViewer version

v0.15.2

### Android version

Android 13

### Device

IQOO Z5

**Comment by YenalyLiew** [comment]
这个bug太奇怪了

**Comment by INKCR0W** [comment]
> 这个bug太奇怪了

是的，明明是同一个回调，给我看猪脑过载了

**Comment by YenalyLiew** [comment]
我直接不让在这里登录了哈哈哈哈哈哈
