### ISSUE TITLE
平板播放时，长按视频稳定报错崩溃

### ISSUE THREAD

**Issue by keruiter** [YenalyLiew/Han1meViewer#28]
![Screenshot_20231203_205133](https://github.com/YenalyLiew/Han1meViewer/assets/98081562/e8426aee-fd6d-4f5c-9767-ff87b1b67f8d)

**Comment by YenalyLiew** [comment]
看看 v0.12.2 还有这问题么

**Comment by keruiter** [comment]
> 看看 v0.12.2 还有这问题么
目前已经没有再崩溃了。本人这方面不太懂，只能贴个bug截图了╯﹏╰，辛苦大大调试了。
关于H帧，老实说最开始觉得只是个标记，作用不大，但刚刚仔细想了一下使用场景后，恍然大悟，只能说“会玩”，属实没想到这方面。但这个功能还是很靠别人分享的数据量，毕竟一个人看的番有限，看过的才好标记，而第一次看就有这种“前方高能”的提示时爽点才最高。前期数据量太少，可能这个功能就比较麻烦了，因为都要自己标。不过数据量起来后感觉这个功能会很赞。
建议的话，把设置里面那个 H帧共享默认打开可能会好一点？或者把哪些番已经被打过H帧可以列出来让用户直接选择感受一下？

**Comment by YenalyLiew** [comment]
那个打开也没用，没人贡献，所以是空的。
目前也可以自己标记，如果需要的话。
但我感觉上手也不难啊。

高潮点暂停，长按标记，回调到x分钟前，x秒钟倒计时提醒。

哪怕标记不全也没啥问题，自己需要哪里标记哪里就行了，主要是看自己需要。如果自己是时间管理大师，每个点都记得清清楚楚，其实也可以把这功能关了😀

**Comment by YenalyLiew** [comment]
> 本人这方面不太懂，只能贴个bug截图了╯﹏╰

不是你的问题，主要是这个快进涉及底层代码，所以那些错误报告有点让人摸不到头脑。
如果还有bug也烦请提出，感谢！
