### ISSUE TITLE
您好，手机开了vpn但是进不去

### ISSUE THREAD

**Issue by Oldsport-996** [YenalyLiew/Han1meViewer#3]
开了分流节点就显示503，开了全局模式就显示collection reset，这该怎么办好

**Comment by YenalyLiew** [comment]
网站加固了，套了一层保护措施，我暂时也没办法，估计是被发现了

**Comment by YenalyLiew** [comment]
本人最近一看，网站不但加固，而且改版了不少。因为这个软件的影响力远不及EhViewer，没有贡献者，而且我最近事情繁多，所以对于破除CloudFlare加固，和对改版后进行重新整合，有点力不从心。其实你可以考虑卸载了，也非常感谢您之前一直使用我做的软件！

**Comment by mapledot** [comment]
> 本人最近一看，网站不但加固，而且改版了不少。因为这个软件的影响力远不及EhViewer，没有贡献者，而且我最近事情繁多，所以对于破除CloudFlare加固，和对改版后进行重新整合，有点力不从心。其实你可以考虑卸载了，也非常感谢您之前一直使用我做的软件！

感谢您的付出和贡献

> 本人最近一看，网站不但加固，而且改版了不少。因为这个软件的影响力远不及EhViewer，没有贡献者，而且我最近事情繁多，所以对于破除CloudFlare加固，和对改版后进行重新整合，有点力不从心。其实你可以考虑卸载了，也非常感谢您之前一直使用我做的软件！

**Comment by wordly123** [comment]
> 本人最近一看，网站不但加固，而且改版了不少。因为这个软件的影响力远不及EhViewer，没有贡献者，而且我最近事情繁多，所以对于破除CloudFlare加固，和对改版后进行重新整合，有点力不从心。其实你可以考虑卸载了，也非常感谢您之前一直使用我做的软件！

感谢 不过还是希望能在用上 我有空看看能不能搞一下

**Comment by hz1235** [comment]
你好这软件可以开源给我嘛我想接手做做

**Comment by deyangyvtian** [comment]
可以参考这个项目是怎么处理防护的https://github.com/niuhuan/nhentai-cross

**Comment by YenalyLiew** [comment]
> 你好这软件可以开源给我嘛我想接手做做

你随便搞就行，我现在已经没时间做了哈哈

**Comment by YenalyLiew** [comment]
> 你好这软件可以开源给我嘛我想接手做做

你随便搞就行，我现在已经没时间做了哈哈

**Comment by YenalyLiew** [comment]
最近又能用了🥲🥲

**Comment by hz1235** [comment]
老兄直接403还是看不了😭😭

**Comment by YenalyLiew** [comment]
> 老兄直接403还是看不了😭😭

不要用日本节点，日本节点就算进官网也会被ban

**Comment by hz1235** [comment]
老兄还有个非常严重的问题你没发现嘛视频没有字幕啊

**Comment by hz1235** [comment]
OVA 今泉ん家はどうやらギャルの溜まり場になってるらしい ＃3
https://hanime1.me/watch?v=39810
- From Han1meViewer -

**Comment by YenalyLiew** [comment]
> 其他的也一样

这个是中字候补啊，没中文字幕的🤨
