### ISSUE TITLE
一下载就会报错

### ISSUE THREAD

**Issue by axlmly** [YenalyLiew/Han1meViewer#34]
![Screenshot_2023-12-11-04-00-17-959_com.yenaly.han1meviewer.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/41771421/44963ebf-5c1c-4282-ad7e-f91fa5ca7606)

**Comment by YenalyLiew** [comment]
你试试可以了么 v0.12.4

**Comment by axlmly** [comment]
> 你试试可以了么 v0.12.4

还是不行
能整个可复制的报错信息栏或者log导出吗

![Screenshot_2023-12-12-06-24-49-119_com.yenaly.han1meviewer.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/41771421/8deccdda-8b32-4338-aad8-68222a9b8e49)

![Screenshot_2023-12-12-06-24-53-648_com.yenaly.han1meviewer.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/41771421/5e8b9916-1d4b-46bc-b7b1-c0fc14fe5c73)

**Comment by YenalyLiew** [comment]
卧槽！我再看看

**Comment by YenalyLiew** [comment]
你再看看

**Comment by axlmly** [comment]
> 你再看看

好了大佬太强了
