### ISSUE TITLE
您好 请问这个问题要如何解决？

### ISSUE THREAD

**Issue by Weiqwertyuiop** [YenalyLiew/Han1meViewer#36]
![Screenshot_2023-12-25-04-10-06-00_5f9b2ef4da6ea616cfec4a63e3cc44b3](https://github.com/YenalyLiew/Han1meViewer/assets/154761180/15852475-6400-4a40-a7b6-d5645fd39ae5)

**Comment by YenalyLiew** [comment]
挂梯子
