### ISSUE TITLE
下载较多个任务的时候会不断弹出下载失败啊三回啊三回

### ISSUE THREAD

**Issue by axlmly** [YenalyLiew/Han1meViewer#37]
然后一直弹这个![-143c0474894badc3.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/41771421/95a518ac-fb12-40e9-825a-9f6ee741bd5a)

过一会就会闪退。

**Comment by YenalyLiew** [comment]
好的我测试一下

**Comment by YenalyLiew** [comment]
你这个我不是很好复现，我尝试连下四个，没有什么问题，可能你这是网络的问题？

我建议三个三个下试试，一下子下太多可能有一些奇怪的bug

**Comment by axlmly** [comment]
> 你这个我不是很好复现，我尝试连下四个，没有什么问题，可能你这是网络的问题？
> 
> 我建议三个三个下试试，一下子下太多可能有一些奇怪的bug

二十多个。我观察到软件好像是同时下载全部的文件，能加个下载同时下载上限吗？和下载每次删除都得一个一个点，能加个框选全部吗

**Comment by YenalyLiew** [comment]
> > 你这个我不是很好复现，我尝试连下四个，没有什么问题，可能你这是网络的问题？
> > 
> > 我建议三个三个下试试，一下子下太多可能有一些奇怪的bug
> 
> 二十多个。我观察到软件好像是同时下载全部的文件，能加个下载同时下载上限吗？和下载每次删除都得一个一个点，能加个框选全部吗

噗，我到时候看看吧，你这个超过我预想的下载上限了，你暂时先三个三个下
