### ISSUE TITLE
解析错误

### ISSUE THREAD

**Issue by dairanyou** [YenalyLiew/Han1meViewer#40]
![Screenshot_2024-01-12-15-00-30-840_com microsoft emmx](https://github.com/YenalyLiew/Han1meViewer/assets/156407182/48e8b044-185c-4ad0-b7b6-de1f0ceb0960)
好像除了里番外的别的都看不了。点击就显示网址解析不大一样，然后跳转到浏览器里的网站

**Comment by YenalyLiew** [comment]
已收到问题，近几天会进行修改
