### ISSUE TITLE
软件登录不了

### ISSUE THREAD

**Issue by 2338319908** [YenalyLiew/Han1meViewer#58]
软件登录不了，登录验证，一直转圈圈 还一直登录验证，无法登录上

**Comment by YenalyLiew** [comment]
你是官方登录还是谷歌登录？

**Comment by YenalyLiew** [comment]
登录不需要验证啊，我这里没有复现你的问题，一切正常

**Comment by 2338319908** [comment]
![Screenshot_20240204_163748.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/158487945/19028864-7033-46c4-995e-3d46249f51ac)

**Comment by 2338319908** [comment]
![Screenshot_20240204_163748.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/158487945/41eb2597-f377-41ea-a1bc-d8f1ca61aa71)
一直验证

**Comment by YenalyLiew** [comment]
你的网络问题，换节点
