### ISSUE TITLE
打开视频提示网址解析不一样

### ISSUE THREAD

**Issue by mymsszh** [YenalyLiew/Han1meViewer#59]
点开视频就会提示这个网址解析不一样然后跳转到网页，换梯子没用直连也是一样，只有里番可以正常在app里看

**Comment by mymsszh** [comment]
版本是0.12.4+23121203

**Comment by YenalyLiew** [comment]
更新最新版本啊。。

**Comment by mymsszh** [comment]
> 更新最新版本啊。。
我检查更新提示检查失败，我还以为这么久没新版本了嘞。。

**Comment by YenalyLiew** [comment]
更新的那个接口每日有限制访问数量，用的人多了就不能用了，得自行来GitHub release里下载🫠
