### ISSUE TITLE
作者大大，网站是不是崩了，现在进不去了

### ISSUE THREAD

**Issue by mwt233** [YenalyLiew/Han1meViewer#66]

**Comment by YenalyLiew** [comment]
网页进不去软件就没用

**Comment by BlacksW1ng** [comment]
> 网页进不去软件就没用

.me域名改成.com就能用了

**Comment by YenalyLiew** [comment]
> > 网页进不去软件就没用
> 
> .me域名改成.com就能用了

还真是！回去我看看，他们该域名了

**Comment by mwt233** [comment]
那是不是最近只能先用网页版了？

**Comment by mwt233** [comment]
> > > 网页进不去软件就没用
> > 
> > 
> > .me域名改成.com就能用了
> 
> 还真是！回去我看看，他们修改域名了

那是不是最近只能先用网页版了？

**Comment by BlacksW1ng** [comment]
> > > 网页进不去软件就没用
> > 
> > 
> > .me域名改成.com就能用了
> 
> 还真是！ 回去我看看，他们修改域名了

等你更新

**Comment by YenalyLiew** [comment]
> > > > 网页进不去软件就没用
> > > 
> > > 
> > > .me域名改成.com就能用了
> > 
> > 还真是！回去我看看，他们修改域名了
> 
> 那是不是最近只能先用网页版了？

是的

**Comment by YenalyLiew** [comment]
网站目前自行恢复了
