### ISSUE TITLE
没想到作者竟然恢复更新，提个意见能不能加个图标

### ISSUE THREAD

**Issue by qa12587** [YenalyLiew/Han1meViewer#7]
没想到作者竟然恢复更新，提个意见能不能加个图标

**Comment by YenalyLiew** [comment]
😭😭😭😭😭

**Comment by qa12587** [comment]
随便弄个简单的，图标清晰就行，比如白底啥底都行加上一个H，到时候有更好的图标就换了，总比没图标好，还有想提个建议，能不能加个隐藏视频进度条的开关

**Comment by YenalyLiew** [comment]
OK我考虑一下

**Comment by rurires** [comment]
我做了个，大伙看看行不行：

![Ha1Icon](https://github.com/YenalyLiew/Han1meViewer/assets/33484515/ade44b35-cfc8-4061-b42a-18bbada38a6d)

**Comment by qa12587** [comment]
牛逼啊，作者如果实在找不到可以先用这个顶下

**Comment by YenalyLiew** [comment]
感谢提供icon，下版本会用上，但还是想问一下你说的隐藏进度条是什么意思

**Comment by qa12587** [comment]
视频全屏模式下。有一个很细的进度条，所以希望能隐藏

**Comment by qa12587** [comment]
底部

**Comment by linmiaoke1990** [comment]
大大，请问v0.10.5版本什么时候更新

**Comment by YenalyLiew** [comment]
更新了
