### ISSUE TITLE
通知bug

### ISSUE THREAD

**Issue by NeKoOuO** [YenalyLiew/Han1meViewer#98]
在下載的時候每跑1%就會跳一次通知音
![IMG_20240326_105630.jpg](https://github.com/YenalyLiew/Han1meViewer/assets/111511925/d09db8be-e3fa-4534-ade8-3e47c189c003)

**Comment by YenalyLiew** [comment]
草！什么玩意，我一直静音，所以没遇到这bug

**Comment by YenalyLiew** [comment]
ci更新一下看看修复没有

**Comment by NeKoOuO** [comment]
> ci更新一下看看修复没有

要再下一個版本才有辦法確認

**Comment by YenalyLiew** [comment]
我12：00之后推送一次🥲

**Comment by YenalyLiew** [comment]
推送了
